# Import tasks
include:
  - project: 'devandgo/gitlab-helper'
    file: '/templates/ci/tag-semantic-release.yml'

# Define stages
stages:
 - tag

# Overrides
tag:
  environment:
    url: https://npm.devandgo.com:2096/-/web/detail/@devandgo/headless-browser
